Добавил авторизацию пользователя
IhorPshenychnyi/nodejs-homework-rest-api pull request #3
Opened 2021-11-21 16:47 UTC by IhorPshenychnyi

Добавил файл .env в gitignore, но почему-то не сработало и он снова закоммитился

2021-11-21 20:58 UTC, KirillKulakow commented on .env
> -DB_HOST=mongodb+srv://Ihor:sYU4tbTqMDOXSWWF@cluster0.2fojn.mongodb.net/db-contacts?retryWrites=true&w=majority
УДАЛИТЬ
и добавить в .gitignore

2021-11-21 20:59 UTC, KirillKulakow commented on controllers/auth/getCurrentUser.js
> +    await User.findOne({ token })
что это и зачем?

2021-11-21 21:00 UTC, KirillKulakow commented on controllers/auth/login.js
> +    if (!user) {
зачем эта проверка?

2021-11-21 21:09 UTC, KirillKulakow commented on controllers/contacts/getAll.js
> +    if (favorite && favorite === 'true') {
это все считаю лишним

2021-11-21 21:09 UTC, KirillKulakow commented on controllers/contacts/getAll.js
> +    const { page, limit, favorite } = req.query
здесь можно поставить по дефолту favorite = false

2021-11-21 21:11 UTC, KirillKulakow commented on controllers/contacts/getAll.js
> +    if (favorite && favorite === 'true') {
в поиск контактов можно добавить { favorite } - Schema Mongoose сам преобразовует типы в тот который указан в схеме

2021-11-21 21:13 UTC, KirillKulakow commented on controllers/contacts/getAll.js
> +    const skip = (page - 1) * limit
для page и limit нужно сделать проверку на число - если не число, выдать ошибку badRequest

2021-11-21 21:14 UTC, KirillKulakow commented on middlewares/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
если сделаю запрос на список контактов без авторизации приложение сломается

2021-11-21 21:16 UTC, KirillKulakow requested changes
Need fix

2021-11-22 19:43 UTC, IhorPshenychnyi commented on .env
> -DB_HOST=mongodb+srv://Ihor:sYU4tbTqMDOXSWWF@cluster0.2fojn.mongodb.net/db-contacts?retryWrites=true&w=majority
done

2021-11-22 19:48 UTC, IhorPshenychnyi commented on controllers/auth/getCurrentUser.js
> +    await User.findOne({ token })
Это шаг 5 из ДЗ, разве его не нужно отдельно создавать?

2021-11-23 19:04 UTC, KirillKulakow commented on controllers/contacts/getAll.js
> +      const contacts = await Contact.find({ owner: _id }).populate(
напиши ты просто await Contact.find({ owner: _id, favorite }) и все

2021-11-23 19:05 UTC, KirillKulakow commented on controllers/contacts/getAll.js
> +      const contacts = await Contact.find({ owner: _id }).populate(
и не нужна тебе фильтрация никакая

2021-11-23 19:06 UTC, KirillKulakow commented on controllers/auth/getCurrentUser.js
> +    await User.findOne({ token })
так а что ты данным методом делаешь?
делаешь запрос в БД на поиск токена, он находит юзера и при этом никуда не записывает
вопрос - зачем?

2021-11-23 19:11 UTC, KirillKulakow commented on controllers/contacts/getAll.js
> +      const contacts = await Contact.find({ owner: _id }).populate(
весь этот файл - слишком растянутый
это все можно уместить максимум в 30 строк

- сначала делаешь проверку page и limit - если не число вернуть ошибку badRequest
- потом вне зависимости какие у тебя параметры делаешь один запрос - 
```
const contacts = await Contact.find(
         { owner: _id },
         '_id name email phone favorite',
         {
           skip,
           limit,
         },
       ).populate('owner', '_id email')
```

2021-11-23 19:12 UTC, KirillKulakow commented on middlewares/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
почему не поправил?

2021-11-23 21:27 UTC, IhorPshenychnyi commented on controllers/contacts/getAll.js
> +      const contacts = await Contact.find({ owner: _id }).populate(
Спасибо, вроде как разобрался.

2021-11-24 20:18 UTC, KirillKulakow approved these changes

2021-11-24 20:19 UTC, KirillKulakow commented
по желанию можешь сделать дом проверку
при поиске/удалении/обновлении контакта по ид добавить поиск и по собственнику контакта
чтобы доступ был только к своим контактам

2021-11-26 18:29 UTC, merged